"""Comprehensive dictionary of Polish cities mapped to voivodeships (regions).

Source: Wikipedia "Miasta w Polsce" (1026 cities as of Jan 2026).
Also includes well-known localities that appear in job listings.
"""

from __future__ import annotations

# canonical city name → voivodeship
CITY_REGION: dict[str, str] = {
    # A
    "Aleksandrów Kujawski": "kujawsko-pomorskie",
    "Aleksandrów Łódzki": "łódzkie",
    "Alwernia": "małopolskie",
    "Andrychów": "małopolskie",
    "Annopol": "lubelskie",
    "Augustów": "podlaskie",
    # B
    "Babimost": "lubuskie",
    "Baborów": "opolskie",
    "Baranów Sandomierski": "podkarpackie",
    "Barcin": "kujawsko-pomorskie",
    "Barczewo": "warmińsko-mazurskie",
    "Bardo": "dolnośląskie",
    "Barlinek": "zachodniopomorskie",
    "Bartoszyce": "warmińsko-mazurskie",
    "Barwice": "zachodniopomorskie",
    "Bełchatów": "łódzkie",
    "Bełżyce": "lubelskie",
    "Będzin": "śląskie",
    "Biała": "opolskie",
    "Biała Piska": "warmińsko-mazurskie",
    "Biała Podlaska": "lubelskie",
    "Biała Rawska": "łódzkie",
    "Białaczów": "łódzkie",
    "Białobrzegi": "mazowieckie",
    "Białogard": "zachodniopomorskie",
    "Biały Bór": "zachodniopomorskie",
    "Białystok": "podlaskie",
    "Biecz": "małopolskie",
    "Bielawa": "dolnośląskie",
    "Bielsk Podlaski": "podlaskie",
    "Bielsko-Biała": "śląskie",
    "Bieruń": "śląskie",
    "Bierutów": "dolnośląskie",
    "Bieżuń": "mazowieckie",
    "Biłgoraj": "lubelskie",
    "Bircza": "podkarpackie",
    "Biskupiec": "warmińsko-mazurskie",
    "Bisztynek": "warmińsko-mazurskie",
    "Blachownia": "śląskie",
    "Błaszki": "łódzkie",
    "Błażowa": "podkarpackie",
    "Błonie": "mazowieckie",
    "Bobolice": "zachodniopomorskie",
    "Bobowa": "małopolskie",
    "Bobrowniki": "kujawsko-pomorskie",
    "Bochnia": "małopolskie",
    "Bodzanów": "mazowieckie",
    "Bodzentyn": "świętokrzyskie",
    "Bogatynia": "dolnośląskie",
    "Bogoria": "świętokrzyskie",
    "Boguchwała": "podkarpackie",
    "Boguszów-Gorce": "dolnośląskie",
    "Bojanowo": "wielkopolskie",
    "Bolesławiec": "dolnośląskie",
    "Bolimów": "łódzkie",
    "Bolków": "dolnośląskie",
    "Borek Wielkopolski": "wielkopolskie",
    "Borne Sulinowo": "zachodniopomorskie",
    "Branice": "opolskie",
    "Braniewo": "warmińsko-mazurskie",
    "Brańsk": "podlaskie",
    "Brodnica": "kujawsko-pomorskie",
    "Brody": "lubuskie",
    "Brok": "mazowieckie",
    "Brusy": "pomorskie",
    "Brwinów": "mazowieckie",
    "Brzeg": "opolskie",
    "Brzeg Dolny": "dolnośląskie",
    "Brzesko": "małopolskie",
    "Brzeszcze": "małopolskie",
    "Brześć Kujawski": "kujawsko-pomorskie",
    "Brzeziny": "łódzkie",
    "Brzostek": "podkarpackie",
    "Brzozów": "podkarpackie",
    "Budzyń": "wielkopolskie",
    "Buk": "wielkopolskie",
    "Bukowno": "małopolskie",
    "Busko-Zdrój": "świętokrzyskie",
    "Bychawa": "lubelskie",
    "Byczyna": "opolskie",
    "Bydgoszcz": "kujawsko-pomorskie",
    "Bystrzyca Kłodzka": "dolnośląskie",
    "Bytom": "śląskie",
    "Bytom Odrzański": "lubuskie",
    "Bytów": "pomorskie",
    # C
    "Cedynia": "zachodniopomorskie",
    "Cegłów": "mazowieckie",
    "Chełm": "lubelskie",
    "Chełmek": "małopolskie",
    "Chełmno": "kujawsko-pomorskie",
    "Chełmża": "kujawsko-pomorskie",
    "Chęciny": "świętokrzyskie",
    "Chmielnik": "świętokrzyskie",
    "Chocianów": "dolnośląskie",
    "Chociwel": "zachodniopomorskie",
    "Chocz": "wielkopolskie",
    "Chodecz": "kujawsko-pomorskie",
    "Chodzież": "wielkopolskie",
    "Chojna": "zachodniopomorskie",
    "Chojnice": "pomorskie",
    "Chojnów": "dolnośląskie",
    "Choroszcz": "podlaskie",
    "Chorzele": "mazowieckie",
    "Chorzów": "śląskie",
    "Choszczno": "zachodniopomorskie",
    "Chrzanów": "małopolskie",
    "Ciechanowiec": "podlaskie",
    "Ciechanów": "mazowieckie",
    "Ciechocinek": "kujawsko-pomorskie",
    "Ciepielów": "mazowieckie",
    "Cieszanów": "podkarpackie",
    "Cieszyn": "śląskie",
    "Ciężkowice": "małopolskie",
    "Cybinka": "lubuskie",
    "Czaplinek": "zachodniopomorskie",
    "Czarna Białostocka": "podlaskie",
    "Czarna Woda": "pomorskie",
    "Czarne": "pomorskie",
    "Czarnków": "wielkopolskie",
    "Czarny Dunajec": "małopolskie",
    "Czchów": "małopolskie",
    "Czechowice-Dziedzice": "śląskie",
    "Czeladź": "śląskie",
    "Czemierniki": "lubelskie",
    "Czempiń": "wielkopolskie",
    "Czerniejewo": "wielkopolskie",
    "Czersk": "pomorskie",
    "Czerwieńsk": "lubuskie",
    "Czerwionka-Leszczyny": "śląskie",
    "Czerwińsk nad Wisłą": "mazowieckie",
    "Częstochowa": "śląskie",
    "Człopa": "zachodniopomorskie",
    "Człuchów": "pomorskie",
    "Czyżew": "podlaskie",
    # Ć
    "Ćmielów": "świętokrzyskie",
    # D
    "Daleszyce": "świętokrzyskie",
    "Darłowo": "zachodniopomorskie",
    "Dąbie": "wielkopolskie",
    "Dąbrowa Białostocka": "podlaskie",
    "Dąbrowa Górnicza": "śląskie",
    "Dąbrowa Tarnowska": "małopolskie",
    "Dąbrowice": "łódzkie",
    "Debrzno": "pomorskie",
    "Dębica": "podkarpackie",
    "Dęblin": "lubelskie",
    "Dębno": "zachodniopomorskie",
    "Dobczyce": "małopolskie",
    "Dobiegniew": "lubuskie",
    "Dobra": "zachodniopomorskie",
    "Dobre": "mazowieckie",
    "Dobre Miasto": "warmińsko-mazurskie",
    "Dobrodzień": "opolskie",
    "Dobrzany": "zachodniopomorskie",
    "Dobrzyca": "wielkopolskie",
    "Dobrzyń nad Wisłą": "kujawsko-pomorskie",
    "Dolsk": "wielkopolskie",
    "Drawno": "zachodniopomorskie",
    "Drawsko Pomorskie": "zachodniopomorskie",
    "Drezdenko": "lubuskie",
    "Drobin": "mazowieckie",
    "Drohiczyn": "podlaskie",
    "Drzewica": "łódzkie",
    "Dubiecko": "podkarpackie",
    "Dukla": "podkarpackie",
    "Duszniki-Zdrój": "dolnośląskie",
    "Dynów": "podkarpackie",
    "Działdowo": "warmińsko-mazurskie",
    "Działoszyce": "świętokrzyskie",
    "Działoszyn": "łódzkie",
    "Dzierzgoń": "pomorskie",
    "Dzierżoniów": "dolnośląskie",
    "Dziwnów": "zachodniopomorskie",
    # E
    "Elbląg": "warmińsko-mazurskie",
    "Ełk": "warmińsko-mazurskie",
    # F
    "Frampol": "lubelskie",
    "Frombork": "warmińsko-mazurskie",
    # G
    "Garwolin": "mazowieckie",
    "Gąbin": "mazowieckie",
    "Gąsawa": "kujawsko-pomorskie",
    "Gdańsk": "pomorskie",
    "Gdynia": "pomorskie",
    "Gielniów": "mazowieckie",
    "Giżycko": "warmińsko-mazurskie",
    "Glinojeck": "mazowieckie",
    "Gliwice": "śląskie",
    "Głogów": "dolnośląskie",
    "Głogów Małopolski": "podkarpackie",
    "Głogówek": "opolskie",
    "Głowaczów": "mazowieckie",
    "Głowno": "łódzkie",
    "Głubczyce": "opolskie",
    "Głuchołazy": "opolskie",
    "Głuszyca": "dolnośląskie",
    "Gniew": "pomorskie",
    "Gniewkowo": "kujawsko-pomorskie",
    "Gniezno": "wielkopolskie",
    "Gogolin": "opolskie",
    "Golczewo": "zachodniopomorskie",
    "Goleniów": "zachodniopomorskie",
    "Golina": "wielkopolskie",
    "Golub-Dobrzyń": "kujawsko-pomorskie",
    "Gołańcz": "wielkopolskie",
    "Gołdap": "warmińsko-mazurskie",
    "Goniądz": "podlaskie",
    "Goraj": "lubelskie",
    "Gorlice": "małopolskie",
    "Gorzów Śląski": "opolskie",
    "Gorzów Wielkopolski": "lubuskie",
    "Gostynin": "mazowieckie",
    "Gostyń": "wielkopolskie",
    "Gościno": "zachodniopomorskie",
    "Gowarczów": "świętokrzyskie",
    "Gozdnica": "lubuskie",
    "Góra": "dolnośląskie",
    "Góra Kalwaria": "mazowieckie",
    "Górowo Iławeckie": "warmińsko-mazurskie",
    "Górzno": "kujawsko-pomorskie",
    "Grabów": "łódzkie",
    "Grabów nad Prosną": "wielkopolskie",
    "Grajewo": "podlaskie",
    "Grodków": "opolskie",
    "Grodzisk Mazowiecki": "mazowieckie",
    "Grodzisk Wielkopolski": "wielkopolskie",
    "Grójec": "mazowieckie",
    "Grudziądz": "kujawsko-pomorskie",
    "Grybów": "małopolskie",
    "Gryfice": "zachodniopomorskie",
    "Gryfino": "zachodniopomorskie",
    "Gryfów Śląski": "dolnośląskie",
    "Gubin": "lubuskie",
    # H
    "Hajnówka": "podlaskie",
    "Halinów": "mazowieckie",
    "Hel": "pomorskie",
    "Hrubieszów": "lubelskie",
    # I
    "Iława": "warmińsko-mazurskie",
    "Iłowa": "lubuskie",
    "Iłża": "mazowieckie",
    "Imielin": "śląskie",
    "Inowłódz": "łódzkie",
    "Inowrocław": "kujawsko-pomorskie",
    "Ińsko": "zachodniopomorskie",
    "Iwaniska": "świętokrzyskie",
    "Iwonicz-Zdrój": "podkarpackie",
    "Izbica": "lubelskie",
    "Izbica Kujawska": "kujawsko-pomorskie",
    # J
    "Jadów": "mazowieckie",
    "Janów": "śląskie",
    "Janów Podlaski": "lubelskie",
    "Jastrzębie-Zdrój": "śląskie",
    "Jabłonowo Pomorskie": "kujawsko-pomorskie",
    "Janikowo": "kujawsko-pomorskie",
    "Janowiec Wielkopolski": "kujawsko-pomorskie",
    "Janów Lubelski": "lubelskie",
    "Jaraczewo": "wielkopolskie",
    "Jarocin": "wielkopolskie",
    "Jarosław": "podkarpackie",
    "Jasień": "lubuskie",
    "Jasło": "podkarpackie",
    "Jastarnia": "pomorskie",
    "Jastrowie": "wielkopolskie",
    "Jastrząb": "mazowieckie",
    "Jawor": "dolnośląskie",
    "Jawornik Polski": "podkarpackie",
    "Jaworzno": "śląskie",
    "Jaworzyna Śląska": "dolnośląskie",
    "Jedlicze": "podkarpackie",
    "Jedlina-Zdrój": "dolnośląskie",
    "Jedlnia-Letnisko": "mazowieckie",
    "Jedwabne": "podlaskie",
    "Jelcz-Laskowice": "dolnośląskie",
    "Jelenia Góra": "dolnośląskie",
    "Jeziorany": "warmińsko-mazurskie",
    "Jeżów": "łódzkie",
    "Jędrzejów": "świętokrzyskie",
    "Jordanów": "małopolskie",
    "Józefów": "mazowieckie",
    "Józefów nad Wisłą": "lubelskie",
    "Jutrosin": "wielkopolskie",
    # K
    "Kaczory": "wielkopolskie",
    "Kalety": "śląskie",
    "Kalisz": "wielkopolskie",
    "Kalisz Pomorski": "zachodniopomorskie",
    "Kalwaria Zebrzydowska": "małopolskie",
    "Kałuszyn": "mazowieckie",
    "Kamieniec Ząbkowicki": "dolnośląskie",
    "Kamienna Góra": "dolnośląskie",
    "Kamień Krajeński": "kujawsko-pomorskie",
    "Kamień Pomorski": "zachodniopomorskie",
    "Kamieńsk": "łódzkie",
    "Kamionka": "lubelskie",
    "Kańczuga": "podkarpackie",
    "Karczew": "mazowieckie",
    "Kargowa": "lubuskie",
    "Karlino": "zachodniopomorskie",
    "Karpacz": "dolnośląskie",
    "Kartuzy": "pomorskie",
    "Katowice": "śląskie",
    "Kazanów": "mazowieckie",
    "Kazimierz Dolny": "lubelskie",
    "Kazimierza Wielka": "świętokrzyskie",
    "Kąty Wrocławskie": "dolnośląskie",
    "Kcynia": "kujawsko-pomorskie",
    "Kędzierzyn-Koźle": "opolskie",
    "Kępice": "pomorskie",
    "Kępno": "wielkopolskie",
    "Kętrzyn": "warmińsko-mazurskie",
    "Kęty": "małopolskie",
    "Kielce": "świętokrzyskie",
    "Kiernozia": "łódzkie",
    "Kietrz": "opolskie",
    "Kikół": "kujawsko-pomorskie",
    "Kisielice": "warmińsko-mazurskie",
    "Kleczew": "wielkopolskie",
    "Kleszczele": "podlaskie",
    "Klimontów": "świętokrzyskie",
    "Kluczbork": "opolskie",
    "Kłecko": "wielkopolskie",
    "Kłobuck": "śląskie",
    "Kłodawa": "wielkopolskie",
    "Kłodzko": "dolnośląskie",
    "Knurów": "śląskie",
    "Knyszyn": "podlaskie",
    "Kobylin": "wielkopolskie",
    "Kobylnica": "pomorskie",
    "Kobyłka": "mazowieckie",
    "Kock": "lubelskie",
    "Kolbuszowa": "podkarpackie",
    "Kolno": "podlaskie",
    "Kolonowskie": "opolskie",
    "Koluszki": "łódzkie",
    "Kołaczyce": "podkarpackie",
    "Koło": "wielkopolskie",
    "Kołobrzeg": "zachodniopomorskie",
    "Koniecpol": "śląskie",
    "Konin": "wielkopolskie",
    "Konstancin-Jeziorna": "mazowieckie",
    "Konstantynów Łódzki": "łódzkie",
    "Końskie": "świętokrzyskie",
    "Końskowola": "lubelskie",
    "Koprzywnica": "świętokrzyskie",
    "Korfantów": "opolskie",
    "Koronowo": "kujawsko-pomorskie",
    "Korsze": "warmińsko-mazurskie",
    "Kosów Lacki": "mazowieckie",
    "Kostrzyn": "wielkopolskie",
    "Kostrzyn nad Odrą": "lubuskie",
    "Koszalin": "zachodniopomorskie",
    "Koszyce": "małopolskie",
    "Kościan": "wielkopolskie",
    "Kościerzyna": "pomorskie",
    "Kowal": "kujawsko-pomorskie",
    "Kowalewo Pomorskie": "kujawsko-pomorskie",
    "Kowary": "dolnośląskie",
    "Koziegłowy": "śląskie",
    "Kozienice": "mazowieckie",
    "Koźmin Wielkopolski": "wielkopolskie",
    "Koźminek": "wielkopolskie",
    "Kożuchów": "lubuskie",
    "Kórnik": "wielkopolskie",
    "Krajenka": "wielkopolskie",
    "Kraków": "małopolskie",
    "Krapkowice": "opolskie",
    "Krasnobród": "lubelskie",
    "Krasnystaw": "lubelskie",
    "Kraśnik": "lubelskie",
    "Krobia": "wielkopolskie",
    "Krosno": "podkarpackie",
    "Krosno Odrzańskie": "lubuskie",
    "Krośniewice": "łódzkie",
    "Krotoszyn": "wielkopolskie",
    "Kruszwica": "kujawsko-pomorskie",
    "Krynica Morska": "pomorskie",
    "Krynica-Zdrój": "małopolskie",
    "Krynki": "podlaskie",
    "Krzanowice": "śląskie",
    "Krzepice": "śląskie",
    "Krzeszowice": "małopolskie",
    "Krzywiń": "wielkopolskie",
    "Krzyż Wielkopolski": "wielkopolskie",
    "Książ Wielki": "małopolskie",
    "Książ Wielkopolski": "wielkopolskie",
    "Kudowa-Zdrój": "dolnośląskie",
    "Kunów": "świętokrzyskie",
    "Kurów": "lubelskie",
    "Kutno": "łódzkie",
    "Kuźnia Raciborska": "śląskie",
    "Kwidzyn": "pomorskie",
    # L
    "Latowicz": "mazowieckie",
    "Lądek-Zdrój": "dolnośląskie",
    "Legionowo": "mazowieckie",
    "Legnica": "dolnośląskie",
    "Lesko": "podkarpackie",
    "Leszno": "wielkopolskie",
    "Leśna": "dolnośląskie",
    "Leśnica": "opolskie",
    "Lewin Brzeski": "opolskie",
    "Leżajsk": "podkarpackie",
    "Lębork": "pomorskie",
    "Lędziny": "śląskie",
    "Libiąż": "małopolskie",
    "Lidzbark": "warmińsko-mazurskie",
    "Lidzbark Warmiński": "warmińsko-mazurskie",
    "Limanowa": "małopolskie",
    "Lipiany": "zachodniopomorskie",
    "Lipno": "kujawsko-pomorskie",
    "Lipsk": "podlaskie",
    "Lipsko": "mazowieckie",
    "Lubaczów": "podkarpackie",
    "Lubań": "dolnośląskie",
    "Lubartów": "lubelskie",
    "Lubawa": "warmińsko-mazurskie",
    "Lubawka": "dolnośląskie",
    "Lubień Kujawski": "kujawsko-pomorskie",
    "Lubin": "dolnośląskie",
    "Lublin": "lubelskie",
    "Lubliniec": "śląskie",
    "Lubniewice": "lubuskie",
    "Lubomierz": "dolnośląskie",
    "Luboń": "wielkopolskie",
    "Lubowidz": "mazowieckie",
    "Lubraniec": "kujawsko-pomorskie",
    "Lubsko": "lubuskie",
    "Lubycza Królewska": "lubelskie",
    "Lutomiersk": "łódzkie",
    "Lututów": "łódzkie",
    "Lwówek": "wielkopolskie",
    "Lwówek Śląski": "dolnośląskie",
    # Ł
    "Łabiszyn": "kujawsko-pomorskie",
    "Łagów": "świętokrzyskie",
    "Łańcut": "podkarpackie",
    "Łapy": "podlaskie",
    "Łasin": "kujawsko-pomorskie",
    "Łask": "łódzkie",
    "Łaskarzew": "mazowieckie",
    "Łaszczów": "lubelskie",
    "Łaziska Górne": "śląskie",
    "Łazy": "śląskie",
    "Łeba": "pomorskie",
    "Łęczna": "lubelskie",
    "Łęczyca": "łódzkie",
    "Łęknica": "lubuskie",
    "Łobez": "zachodniopomorskie",
    "Łobżenica": "wielkopolskie",
    "Łochów": "mazowieckie",
    "Łomianki": "mazowieckie",
    "Łomża": "podlaskie",
    "Łopuszno": "świętokrzyskie",
    "Łosice": "mazowieckie",
    "Łowicz": "łódzkie",
    "Łódź": "łódzkie",
    "Łuków": "lubelskie",
    # M
    "Maciejowice": "mazowieckie",
    "Magnuszew": "mazowieckie",
    "Maków Mazowiecki": "mazowieckie",
    "Maków Podhalański": "małopolskie",
    "Malbork": "pomorskie",
    "Małkinia Górna": "mazowieckie",
    "Małogoszcz": "świętokrzyskie",
    "Małomice": "lubuskie",
    "Margonin": "wielkopolskie",
    "Marki": "mazowieckie",
    "Maszewo": "zachodniopomorskie",
    "Miasteczko Krajeńskie": "wielkopolskie",
    "Miasteczko Śląskie": "śląskie",
    "Miastko": "pomorskie",
    "Michałowo": "podlaskie",
    "Miechów": "małopolskie",
    "Miejska Górka": "wielkopolskie",
    "Mielec": "podkarpackie",
    "Mielno": "zachodniopomorskie",
    "Mieroszów": "dolnośląskie",
    "Mieszkowice": "zachodniopomorskie",
    "Mieścisko": "wielkopolskie",
    "Międzybórz": "dolnośląskie",
    "Międzychód": "wielkopolskie",
    "Międzylesie": "dolnośląskie",
    "Międzyrzec Podlaski": "lubelskie",
    "Międzyrzecz": "lubuskie",
    "Międzyzdroje": "zachodniopomorskie",
    "Miękinia": "dolnośląskie",
    "Mikołajki": "warmińsko-mazurskie",
    "Mikołów": "śląskie",
    "Mikstat": "wielkopolskie",
    "Milanówek": "mazowieckie",
    "Milicz": "dolnośląskie",
    "Miłakowo": "warmińsko-mazurskie",
    "Miłomłyn": "warmińsko-mazurskie",
    "Miłosław": "wielkopolskie",
    "Mińsk Mazowiecki": "mazowieckie",
    "Mirosławiec": "zachodniopomorskie",
    "Mirsk": "dolnośląskie",
    "Mława": "mazowieckie",
    "Młynary": "warmińsko-mazurskie",
    "Modliborzyce": "lubelskie",
    "Mogielnica": "mazowieckie",
    "Mogilno": "kujawsko-pomorskie",
    "Mońki": "podlaskie",
    "Morawica": "świętokrzyskie",
    "Morąg": "warmińsko-mazurskie",
    "Mordy": "mazowieckie",
    "Moryń": "zachodniopomorskie",
    "Mosina": "wielkopolskie",
    "Mrągowo": "warmińsko-mazurskie",
    "Mrocza": "kujawsko-pomorskie",
    "Mrozy": "mazowieckie",
    "Mszana Dolna": "małopolskie",
    "Mszczonów": "mazowieckie",
    "Murowana Goślina": "wielkopolskie",
    "Muszyna": "małopolskie",
    "Mysłowice": "śląskie",
    "Myszków": "śląskie",
    "Myszyniec": "mazowieckie",
    "Myślenice": "małopolskie",
    "Myślibórz": "zachodniopomorskie",
    # N
    "Nakło nad Notecią": "kujawsko-pomorskie",
    "Nałęczów": "lubelskie",
    "Namysłów": "opolskie",
    "Narol": "podkarpackie",
    "Nasielsk": "mazowieckie",
    "Nekla": "wielkopolskie",
    "Nidzica": "warmińsko-mazurskie",
    "Niemcza": "dolnośląskie",
    "Niemodlin": "opolskie",
    "Niepołomice": "małopolskie",
    "Nieszawa": "kujawsko-pomorskie",
    "Nisko": "podkarpackie",
    "Nowa Dęba": "podkarpackie",
    "Nowa Ruda": "dolnośląskie",
    "Nowa Sarzyna": "podkarpackie",
    "Nowa Słupia": "świętokrzyskie",
    "Nowa Sól": "lubuskie",
    "Nowe": "kujawsko-pomorskie",
    "Nowe Brzesko": "małopolskie",
    "Nowe Miasteczko": "lubuskie",
    "Nowe Miasto": "mazowieckie",
    "Nowe Miasto Lubawskie": "warmińsko-mazurskie",
    "Nowe Miasto nad Pilicą": "mazowieckie",
    "Nowe Skalmierzyce": "wielkopolskie",
    "Nowe Warpno": "zachodniopomorskie",
    "Nowogard": "zachodniopomorskie",
    "Nowogrodziec": "dolnośląskie",
    "Nowogród": "podlaskie",
    "Nowogród Bobrzański": "lubuskie",
    "Nowy Dwór Gdański": "pomorskie",
    "Nowy Dwór Mazowiecki": "mazowieckie",
    "Nowy Korczyn": "świętokrzyskie",
    "Nowy Sącz": "małopolskie",
    "Nowy Staw": "pomorskie",
    "Nowy Targ": "małopolskie",
    "Nowy Tomyśl": "wielkopolskie",
    "Nowy Wiśnicz": "małopolskie",
    "Nysa": "opolskie",
    # O
    "Oborniki": "wielkopolskie",
    "Oborniki Śląskie": "dolnośląskie",
    "Obrzycko": "wielkopolskie",
    "Odolanów": "wielkopolskie",
    "Odrzywół": "mazowieckie",
    "Ogrodzieniec": "śląskie",
    "Okonek": "wielkopolskie",
    "Olecko": "warmińsko-mazurskie",
    "Olesno": "opolskie",
    "Oleszyce": "podkarpackie",
    "Oleśnica": "dolnośląskie",
    "Olkusz": "małopolskie",
    "Olsztyn": "warmińsko-mazurskie",
    "Olsztynek": "warmińsko-mazurskie",
    "Olszyna": "dolnośląskie",
    "Oława": "dolnośląskie",
    "Opalenica": "wielkopolskie",
    "Opatowiec": "świętokrzyskie",
    "Opatów": "świętokrzyskie",
    "Opatówek": "wielkopolskie",
    "Opoczno": "łódzkie",
    "Opole": "opolskie",
    "Opole Lubelskie": "lubelskie",
    "Orneta": "warmińsko-mazurskie",
    "Orzesze": "śląskie",
    "Orzysz": "warmińsko-mazurskie",
    "Osieck": "mazowieckie",
    "Osieczna": "wielkopolskie",
    "Osiek": "świętokrzyskie",
    "Osjaków": "łódzkie",
    "Ostrołęka": "mazowieckie",
    "Ostroróg": "wielkopolskie",
    "Ostrowiec Świętokrzyski": "świętokrzyskie",
    "Ostróda": "warmińsko-mazurskie",
    "Ostrów Lubelski": "lubelskie",
    "Ostrów Mazowiecka": "mazowieckie",
    "Ostrów Wielkopolski": "wielkopolskie",
    "Ostrzeszów": "wielkopolskie",
    "Ośno Lubuskie": "lubuskie",
    "Oświęcim": "małopolskie",
    "Otmuchów": "opolskie",
    "Otwock": "mazowieckie",
    "Otyń": "lubuskie",
    "Ozimek": "opolskie",
    "Ozorków": "łódzkie",
    "Ożarów": "świętokrzyskie",
    "Ożarów Mazowiecki": "mazowieckie",
    # P
    "Pabianice": "łódzkie",
    "Pacanów": "świętokrzyskie",
    "Paczków": "opolskie",
    "Pajęczno": "łódzkie",
    "Pakość": "kujawsko-pomorskie",
    "Parczew": "lubelskie",
    "Parzęczew": "łódzkie",
    "Pasłęk": "warmińsko-mazurskie",
    "Pasym": "warmińsko-mazurskie",
    "Pelplin": "pomorskie",
    "Pełczyce": "zachodniopomorskie",
    "Piaseczno": "mazowieckie",
    "Piaski": "lubelskie",
    "Piastów": "mazowieckie",
    "Piątek": "łódzkie",
    "Piechowice": "dolnośląskie",
    "Piekary Śląskie": "śląskie",
    "Piekoszów": "świętokrzyskie",
    "Pieniężno": "warmińsko-mazurskie",
    "Pieńsk": "dolnośląskie",
    "Pierzchnica": "świętokrzyskie",
    "Pieszyce": "dolnośląskie",
    "Pilawa": "mazowieckie",
    "Pilica": "śląskie",
    "Pilzno": "podkarpackie",
    "Piła": "wielkopolskie",
    "Piława Górna": "dolnośląskie",
    "Pińczów": "świętokrzyskie",
    "Pionki": "mazowieckie",
    "Piotrków Kujawski": "kujawsko-pomorskie",
    "Piotrków Trybunalski": "łódzkie",
    "Pisz": "warmińsko-mazurskie",
    "Piszczac": "lubelskie",
    "Piwniczna-Zdrój": "małopolskie",
    "Pleszew": "wielkopolskie",
    "Płock": "mazowieckie",
    "Płońsk": "mazowieckie",
    "Płoty": "zachodniopomorskie",
    "Pniewy": "wielkopolskie",
    "Pobiedziska": "wielkopolskie",
    "Poddębice": "łódzkie",
    "Podkowa Leśna": "mazowieckie",
    "Pogorzela": "wielkopolskie",
    "Polanica-Zdrój": "dolnośląskie",
    "Polanów": "zachodniopomorskie",
    "Police": "zachodniopomorskie",
    "Polkowice": "dolnośląskie",
    "Połaniec": "świętokrzyskie",
    "Połczyn-Zdrój": "zachodniopomorskie",
    "Poniatowa": "lubelskie",
    "Poniec": "wielkopolskie",
    "Poręba": "śląskie",
    "Poznań": "wielkopolskie",
    "Prabuty": "pomorskie",
    "Praszka": "opolskie",
    "Prochowice": "dolnośląskie",
    "Proszowice": "małopolskie",
    "Prószków": "opolskie",
    "Pruchnik": "podkarpackie",
    "Prudnik": "opolskie",
    "Prusice": "dolnośląskie",
    "Pruszcz": "kujawsko-pomorskie",
    "Pruszcz Gdański": "pomorskie",
    "Pruszków": "mazowieckie",
    "Przasnysz": "mazowieckie",
    "Przecław": "podkarpackie",
    "Przedbórz": "łódzkie",
    "Przedecz": "wielkopolskie",
    "Przemków": "dolnośląskie",
    "Przemyśl": "podkarpackie",
    "Przeworsk": "podkarpackie",
    "Przyrów": "śląskie",
    "Przysucha": "mazowieckie",
    "Przytyk": "mazowieckie",
    "Pszczyna": "śląskie",
    "Pszów": "śląskie",
    "Puck": "pomorskie",
    "Puławy": "lubelskie",
    "Pułtusk": "mazowieckie",
    "Puszczykowo": "wielkopolskie",
    "Pyrzyce": "zachodniopomorskie",
    "Pyskowice": "śląskie",
    "Pyzdry": "wielkopolskie",
    # R
    "Rabka-Zdrój": "małopolskie",
    "Raciąż": "mazowieckie",
    "Racibórz": "śląskie",
    "Radków": "dolnośląskie",
    "Radlin": "śląskie",
    "Radłów": "małopolskie",
    "Radom": "mazowieckie",
    "Radomsko": "łódzkie",
    "Radoszyce": "świętokrzyskie",
    "Radymno": "podkarpackie",
    "Radzymin": "mazowieckie",
    "Radzyń Podlaski": "lubelskie",
    "Rajgród": "podlaskie",
    "Rakoniewice": "wielkopolskie",
    "Raszków": "wielkopolskie",
    "Rawa Mazowiecka": "łódzkie",
    "Rawicz": "wielkopolskie",
    "Recz": "zachodniopomorskie",
    "Reda": "pomorskie",
    "Rejowiec": "lubelskie",
    "Rejowiec Fabryczny": "lubelskie",
    "Resko": "zachodniopomorskie",
    "Reszel": "warmińsko-mazurskie",
    "Rogoźno": "wielkopolskie",
    "Ropczyce": "podkarpackie",
    "Rozprza": "łódzkie",
    "Różan": "mazowieckie",
    "Ruciane-Nida": "warmińsko-mazurskie",
    "Ruda Śląska": "śląskie",
    "Rudnik nad Sanem": "podkarpackie",
    "Rumia": "pomorskie",
    "Rybnik": "śląskie",
    "Rychtal": "wielkopolskie",
    "Rychwał": "wielkopolskie",
    "Rydułtowy": "śląskie",
    "Rydzyna": "wielkopolskie",
    "Ryglice": "małopolskie",
    "Ryki": "lubelskie",
    "Rymanów": "podkarpackie",
    "Ryn": "warmińsko-mazurskie",
    "Rypin": "kujawsko-pomorskie",
    "Rzepin": "lubuskie",
    "Rzeszów": "podkarpackie",
    "Rzgów": "łódzkie",
    # S
    "Sandomierz": "świętokrzyskie",
    "Sanniki": "mazowieckie",
    "Sanok": "podkarpackie",
    "Sejny": "podlaskie",
    "Serock": "mazowieckie",
    "Sędziszów": "świętokrzyskie",
    "Sędziszów Małopolski": "podkarpackie",
    "Sępopol": "warmińsko-mazurskie",
    "Sępólno Krajeńskie": "kujawsko-pomorskie",
    "Sianów": "zachodniopomorskie",
    "Siechnice": "dolnośląskie",
    "Siedlce": "mazowieckie",
    "Siedliszcze": "lubelskie",
    "Siemianowice Śląskie": "śląskie",
    "Siemiatycze": "podlaskie",
    "Sieniawa": "podkarpackie",
    "Siennica": "mazowieckie",
    "Sienno": "mazowieckie",
    "Sieradz": "łódzkie",
    "Sieraków": "wielkopolskie",
    "Sierpc": "mazowieckie",
    "Siewierz": "śląskie",
    "Skalbmierz": "świętokrzyskie",
    "Skała": "małopolskie",
    "Skarszewy": "pomorskie",
    "Skaryszew": "mazowieckie",
    "Skarżysko-Kamienna": "świętokrzyskie",
    "Skawina": "małopolskie",
    "Skępe": "kujawsko-pomorskie",
    "Skierniewice": "łódzkie",
    "Skoczów": "śląskie",
    "Skoki": "wielkopolskie",
    "Skórcz": "pomorskie",
    "Skwierzyna": "lubuskie",
    "Sława": "lubuskie",
    "Sławków": "śląskie",
    "Sławno": "zachodniopomorskie",
    "Słomniki": "małopolskie",
    "Słubice": "lubuskie",
    "Słupca": "wielkopolskie",
    "Słupsk": "pomorskie",
    "Sobków": "świętokrzyskie",
    "Sobótka": "dolnośląskie",
    "Sochaczew": "mazowieckie",
    "Sochocin": "mazowieckie",
    "Sokołów Małopolski": "podkarpackie",
    "Sokołów Podlaski": "mazowieckie",
    "Sokółka": "podlaskie",
    "Solec Kujawski": "kujawsko-pomorskie",
    "Solec nad Wisłą": "mazowieckie",
    "Sompolno": "wielkopolskie",
    "Sopot": "pomorskie",
    "Sosnowiec": "śląskie",
    "Sośnicowice": "śląskie",
    "Stalowa Wola": "podkarpackie",
    "Stanisławów": "mazowieckie",
    "Starachowice": "świętokrzyskie",
    "Stargard": "zachodniopomorskie",
    "Starogard Gdański": "pomorskie",
    "Staroźreby": "mazowieckie",
    "Stary Sącz": "małopolskie",
    "Staszów": "świętokrzyskie",
    "Stawiski": "podlaskie",
    "Stawiszyn": "wielkopolskie",
    "Stąporków": "świętokrzyskie",
    "Stepnica": "zachodniopomorskie",
    "Stęszew": "wielkopolskie",
    "Stoczek Łukowski": "lubelskie",
    "Stopnica": "świętokrzyskie",
    "Stronie Śląskie": "dolnośląskie",
    "Strumień": "śląskie",
    "Stryków": "łódzkie",
    "Strzegom": "dolnośląskie",
    "Strzelce Krajeńskie": "lubuskie",
    "Strzelce Opolskie": "opolskie",
    "Strzeleczki": "opolskie",
    "Strzelin": "dolnośląskie",
    "Strzelno": "kujawsko-pomorskie",
    "Strzyżów": "podkarpackie",
    "Sucha Beskidzka": "małopolskie",
    "Suchań": "zachodniopomorskie",
    "Suchedniów": "świętokrzyskie",
    "Suchowola": "podlaskie",
    "Sulechów": "lubuskie",
    "Sulejów": "łódzkie",
    "Sulejówek": "mazowieckie",
    "Sulęcin": "lubuskie",
    "Sulmierzyce": "wielkopolskie",
    "Sułkowice": "małopolskie",
    "Supraśl": "podlaskie",
    "Suraż": "podlaskie",
    "Susz": "warmińsko-mazurskie",
    "Suwałki": "podlaskie",
    "Swarzędz": "wielkopolskie",
    "Syców": "dolnośląskie",
    "Szadek": "łódzkie",
    "Szamocin": "wielkopolskie",
    "Szamotuły": "wielkopolskie",
    "Szczawnica": "małopolskie",
    "Szczawno-Zdrój": "dolnośląskie",
    "Szczebrzeszyn": "lubelskie",
    "Szczecin": "zachodniopomorskie",
    "Szczecinek": "zachodniopomorskie",
    "Szczekociny": "śląskie",
    "Szczucin": "małopolskie",
    "Szczuczyn": "podlaskie",
    "Szczyrk": "śląskie",
    "Szczytna": "dolnośląskie",
    "Szczytno": "warmińsko-mazurskie",
    "Szepietowo": "podlaskie",
    "Szklarska Poręba": "dolnośląskie",
    "Szlichtyngowa": "lubuskie",
    "Szprotawa": "lubuskie",
    "Sztum": "pomorskie",
    "Szubin": "kujawsko-pomorskie",
    "Szydłów": "świętokrzyskie",
    "Szydłowiec": "mazowieckie",
    # Ś
    "Ścinawa": "dolnośląskie",
    "Ślesin": "wielkopolskie",
    "Śmigiel": "wielkopolskie",
    "Śrem": "wielkopolskie",
    "Środa Śląska": "dolnośląskie",
    "Środa Wielkopolska": "wielkopolskie",
    "Świątniki Górne": "małopolskie",
    "Świdnica": "dolnośląskie",
    "Świdnik": "lubelskie",
    "Świdwin": "zachodniopomorskie",
    "Świebodzice": "dolnośląskie",
    "Świebodzin": "lubuskie",
    "Świecie": "kujawsko-pomorskie",
    "Świeradów-Zdrój": "dolnośląskie",
    "Świerzawa": "dolnośląskie",
    "Świętochłowice": "śląskie",
    "Świnoujście": "zachodniopomorskie",
    # T
    "Tarczyn": "mazowieckie",
    "Tarnobrzeg": "podkarpackie",
    "Tarnogród": "lubelskie",
    "Tarnowskie Góry": "śląskie",
    "Tarnów": "małopolskie",
    "Tczew": "pomorskie",
    "Terespol": "lubelskie",
    "Tłuszcz": "mazowieckie",
    "Tolkmicko": "warmińsko-mazurskie",
    "Tomaszów Lubelski": "lubelskie",
    "Tomaszów Mazowiecki": "łódzkie",
    "Toruń": "kujawsko-pomorskie",
    "Torzym": "lubuskie",
    "Toszek": "śląskie",
    "Trzcianka": "wielkopolskie",
    "Trzciel": "lubuskie",
    "Trzcińsko-Zdrój": "zachodniopomorskie",
    "Trzebiatów": "zachodniopomorskie",
    "Trzebinia": "małopolskie",
    "Trzebnica": "dolnośląskie",
    "Trzemeszno": "wielkopolskie",
    "Tuchola": "kujawsko-pomorskie",
    "Tuchów": "małopolskie",
    "Tuczno": "zachodniopomorskie",
    "Tuliszków": "wielkopolskie",
    "Tułowice": "opolskie",
    "Turek": "wielkopolskie",
    "Turobin": "lubelskie",
    "Tuszyn": "łódzkie",
    "Twardogóra": "dolnośląskie",
    "Tychowo": "zachodniopomorskie",
    "Tychy": "śląskie",
    "Tyczyn": "podkarpackie",
    "Tykocin": "podlaskie",
    "Tyszowce": "lubelskie",
    # U
    "Ujazd": "opolskie",
    "Ujście": "wielkopolskie",
    "Ulanów": "podkarpackie",
    "Uniejów": "łódzkie",
    "Urzędów": "lubelskie",
    "Ustka": "pomorskie",
    "Ustroń": "śląskie",
    "Ustrzyki Dolne": "podkarpackie",
    # W
    "Wadowice": "małopolskie",
    "Wałbrzych": "dolnośląskie",
    "Wałcz": "zachodniopomorskie",
    "Warka": "mazowieckie",
    "Warszawa": "mazowieckie",
    "Warta": "łódzkie",
    "Wasilków": "podlaskie",
    "Wąbrzeźno": "kujawsko-pomorskie",
    "Wąchock": "świętokrzyskie",
    "Wągrowiec": "wielkopolskie",
    "Wąsosz": "dolnośląskie",
    "Wąwolnica": "lubelskie",
    "Wejherowo": "pomorskie",
    "Węgliniec": "dolnośląskie",
    "Węgorzewo": "warmińsko-mazurskie",
    "Węgorzyno": "zachodniopomorskie",
    "Węgrów": "mazowieckie",
    "Wiązów": "dolnośląskie",
    "Wielbark": "warmińsko-mazurskie",
    "Wieleń": "wielkopolskie",
    "Wielichowo": "wielkopolskie",
    "Wieliczka": "małopolskie",
    "Wieluń": "łódzkie",
    "Wieruszów": "łódzkie",
    "Więcbork": "kujawsko-pomorskie",
    "Wilamowice": "śląskie",
    "Wiskitki": "mazowieckie",
    "Wisła": "śląskie",
    "Wiślica": "świętokrzyskie",
    "Witkowo": "wielkopolskie",
    "Witnica": "lubuskie",
    "Wleń": "dolnośląskie",
    "Władysławowo": "pomorskie",
    "Włocławek": "kujawsko-pomorskie",
    "Włodawa": "lubelskie",
    "Włodowice": "śląskie",
    "Włoszczowa": "świętokrzyskie",
    "Wodzisław": "świętokrzyskie",
    "Wodzisław Śląski": "śląskie",
    "Wojcieszów": "dolnośląskie",
    "Wojkowice": "śląskie",
    "Wojnicz": "małopolskie",
    "Wolbórz": "łódzkie",
    "Wolbrom": "małopolskie",
    "Wolin": "zachodniopomorskie",
    "Wolsztyn": "wielkopolskie",
    "Wołczyn": "opolskie",
    "Wołomin": "mazowieckie",
    "Wołów": "dolnośląskie",
    "Woźniki": "śląskie",
    "Wrocław": "dolnośląskie",
    "Wronki": "wielkopolskie",
    "Września": "wielkopolskie",
    "Wschowa": "lubuskie",
    "Wyrzysk": "wielkopolskie",
    "Wysoka": "wielkopolskie",
    "Wysokie Mazowieckie": "podlaskie",
    "Wyszków": "mazowieckie",
    "Wyszogród": "mazowieckie",
    "Wyśmierzyce": "mazowieckie",
    # Z
    "Zabłudów": "podlaskie",
    "Zabrze": "śląskie",
    "Zagórów": "wielkopolskie",
    "Zagórz": "podkarpackie",
    "Zakliczyn": "małopolskie",
    "Zaklików": "podkarpackie",
    "Zakopane": "małopolskie",
    "Zakroczym": "mazowieckie",
    "Zalewo": "warmińsko-mazurskie",
    "Zambrów": "podlaskie",
    "Zamość": "lubelskie",
    "Zaniemyśl": "wielkopolskie",
    "Zator": "małopolskie",
    "Zawadzkie": "opolskie",
    "Zawichost": "świętokrzyskie",
    "Zawidów": "dolnośląskie",
    "Zawiercie": "śląskie",
    "Ząbki": "mazowieckie",
    "Ząbkowice Śląskie": "dolnośląskie",
    "Zbąszynek": "lubuskie",
    "Zbąszyń": "wielkopolskie",
    "Zduny": "wielkopolskie",
    "Zduńska Wola": "łódzkie",
    "Zdzieszowice": "opolskie",
    "Zelów": "łódzkie",
    "Zgierz": "łódzkie",
    "Zgorzelec": "dolnośląskie",
    "Zielona Góra": "lubuskie",
    "Zielonka": "mazowieckie",
    "Ziębice": "dolnośląskie",
    "Złocieniec": "zachodniopomorskie",
    "Złoczew": "łódzkie",
    "Złotoryja": "dolnośląskie",
    "Złotów": "wielkopolskie",
    "Złoty Stok": "dolnośląskie",
    "Zwierzyniec": "lubelskie",
    "Zwoleń": "mazowieckie",
    # Ż
    "Żabno": "małopolskie",
    "Żagań": "lubuskie",
    "Żarki": "śląskie",
    "Żarnów": "łódzkie",
    "Żarów": "dolnośląskie",
    "Żary": "lubuskie",
    "Żelechów": "mazowieckie",
    "Żerków": "wielkopolskie",
    "Żmigród": "dolnośląskie",
    "Żnin": "kujawsko-pomorskie",
    "Żory": "śląskie",
    "Żukowo": "pomorskie",
    "Żuromin": "mazowieckie",
    "Żychlin": "łódzkie",
    "Żyrardów": "mazowieckie",
    "Żywiec": "śląskie",
}

# Well-known localities / suburbs that appear in job listings but are not cities
LOCALITY_REGION: dict[str, str] = {
    "Dziekanów Leśny": "mazowieckie",
    "Józefosław": "mazowieckie",
    "Janki": "mazowieckie",
    "Raszyn": "mazowieckie",
    "Nadarzyn": "mazowieckie",
    "Lesznowola": "mazowieckie",
    "Stara Iwiczna": "mazowieckie",
    "Magdalenka": "mazowieckie",
    "Wilcza Góra": "mazowieckie",
    "Ursus": "mazowieckie",
    "Kabaty": "mazowieckie",
    "Wilanów": "mazowieckie",
    "Mokotów": "mazowieckie",
    "Wola": "mazowieckie",
    "Żoliborz": "mazowieckie",
    "Ochota": "mazowieckie",
    "Ursynów": "mazowieckie",
    "Bemowo": "mazowieckie",
    "Bielany": "mazowieckie",
    "Targówek": "mazowieckie",
    "Praga": "mazowieckie",
    "Tarchomin": "mazowieckie",
    "Białołęka": "mazowieckie",
    "Wesoła": "mazowieckie",
    "Wawer": "mazowieckie",
    "Michałowice": "mazowieckie",
    "Łomianki Dolne": "mazowieckie",
    "Jabłonna": "mazowieckie",
    "Izabelin": "mazowieckie",
    "Falenty": "mazowieckie",
    "Stare Babice": "mazowieckie",
    "Kobierzyce": "dolnośląskie",
    "Bielany Wrocławskie": "dolnośląskie",
    "Długołęka": "dolnośląskie",
    "Tyniec Mały": "dolnośląskie",
    "Zabierzów": "małopolskie",
    "Wielka Wieś": "małopolskie",
    "Modlniczka": "małopolskie",
    "Zielonki": "małopolskie",
    "Balice": "małopolskie",
    "Kokotów": "małopolskie",
    "Katowice-Ligota": "śląskie",
    "Katowice-Brynów": "śląskie",
}

# Extra aliases: English names, common misspellings, etc.
EXTRA_ALIASES: dict[str, str] = {
    "warsaw": "Warszawa",
    "cracow": "Kraków",
    "breslau": "Wrocław",
    "danzig": "Gdańsk",
    "stettin": "Szczecin",
    "posen": "Poznań",
    "lemberg": "Lwówek Śląski",
    "thorn": "Toruń",
    "bromberg": "Bydgoszcz",
    "elbing": "Elbląg",
    "kattowitz": "Katowice",
    "oppeln": "Opole",
    "gleiwitz": "Gliwice",
    "remote": "Remote",
    "zdalna": "Remote",
    "praca zdalna": "Remote",
}

# Polish diacritics → ASCII mapping
_POLISH_CHARS = str.maketrans(
    "ąćęłńóśźżĄĆĘŁŃÓŚŹŻ",
    "acelnoszżACELNOSZZ",
)
# Second pass for ż→z (maketrans handles single chars)
_POLISH_CHARS_FULL = {
    "ą": "a", "ć": "c", "ę": "e", "ł": "l", "ń": "n",
    "ó": "o", "ś": "s", "ź": "z", "ż": "z",
    "Ą": "A", "Ć": "C", "Ę": "E", "Ł": "L", "Ń": "N",
    "Ó": "O", "Ś": "S", "Ź": "Z", "Ż": "Z",
}


def _strip_diacritics(text: str) -> str:
    """Remove Polish diacritics from text."""
    result = []
    for ch in text:
        result.append(_POLISH_CHARS_FULL.get(ch, ch))
    return "".join(result)


def _has_diacritics(text: str) -> bool:
    return any(ch in _POLISH_CHARS_FULL for ch in text)


def build_city_aliases() -> dict[str, str]:
    """Build a complete lookup: lowercase variant → canonical city name."""
    aliases: dict[str, str] = {}

    all_cities = {**CITY_REGION, **LOCALITY_REGION}

    for canonical in all_cities:
        key = canonical.lower()
        aliases[key] = canonical

        # Generate ASCII variant if city has diacritics
        if _has_diacritics(canonical):
            ascii_key = _strip_diacritics(canonical).lower()
            if ascii_key != key:
                aliases[ascii_key] = canonical

    # Add extra aliases (English names, etc.)
    for alias_key, canonical in EXTRA_ALIASES.items():
        aliases[alias_key] = canonical

    return aliases


def build_city_to_region() -> dict[str, str]:
    """Build canonical city name → region mapping."""
    mapping = dict(CITY_REGION)
    mapping.update(LOCALITY_REGION)
    return mapping
